### ISSUE TITLE
configuration example file not clear enough

### ISSUE THREAD

**Issue by rickysarraf** [feed2imap/feed2imap#15]
The feed2imaprc example configuration is not clear enough about how a maildir target should be configured. All examples are about IMAP.

It currently reads

```
# Per-feed options:
# name: name of the feed (must be unique)
# url: HTTP[S] address where the feed has to be fetched
# target: the IMAP URI where to put emails. Should start with imap:// for IMAP,
#   imaps:// for IMAPS and maildir:// for a path to a local maildir.
```

and examples

```
# If your login contains an @ character, replace it with %40. Other reserved
# characters can be escaped in the same way (see man ascii to get their code)
feeds:
  - name: feed2imap
    url: http://home.gna.org/feed2imap/feed2imap.rss
    target: imap://luser:password@imap.apinc.org/INBOX.Feeds.Feed2Imap
  - name: lucas
    url: http://www.lucas-nussbaum.net/blog/?feed=rss2
    target: imap://luser:password@imap.apinc.org/INBOX.Feeds.Lucas
  - name: JabberFrWiki
    url: http://wiki.jabberfr.org/index.php?title=Special:Recentchanges&feed=rss
    target: imaps://luser:password@imap.apinc.org/INBOX.Feeds.JabberFR
    always-new: true
  - name: LeMonde
    execurl: "wget -q -O /dev/stdout http://www.lemonde.fr/rss/sequence/0,2-3208,1-0,0.xml"
    filter: "/home/lucas/lemonde_getbody"
    target: imap://luser:password@imap.apinc.org/INBOX.Feeds.LeMonde
# It is also possible to reuse the same string in the target parameter:
# target-refix: &target "imap://user:pass@host/rss."
```

Even the error messages are not clear enough. IMO, they are kinda misleading by mentioning about IMAP errors.

```
rrs@learner:/usr/share/doc/feed2imap$ feed2imap
W, [2016-11-01T23:28:17.822969 #12885]  WARN -- : Configuration file is readable by other users. It probably contains your password.
W, [2016-11-01T23:28:17.823768 #12885]  WARN -- : Cache file /home/rrs/.feed2imap.cache not found, using a new one
F, [2016-11-01T23:28:19.114453 #12885] FATAL -- : Exception caught while uploading mail to /Maildir/RSS: Permission denied @ dir_s_mkdir - /Maildir
/usr/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir'
/usr/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
/usr/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
/usr/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
/usr/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
/usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
/usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
/usr/lib/ruby/vendor_ruby/feed2imap/maildir.rb:160:in `block in guarantee_maildir'
/usr/lib/ruby/vendor_ruby/feed2imap/maildir.rb:159:in `each'
/usr/lib/ruby/vendor_ruby/feed2imap/maildir.rb:159:in `guarantee_maildir'
/usr/lib/ruby/vendor_ruby/feed2imap/maildir.rb:96:in `store_message'
/usr/lib/ruby/vendor_ruby/feed2imap/maildir.rb:33:in `putmail'
/usr/lib/ruby/vendor_ruby/feed2imap/feed2imap.rb:261:in `block (2 levels) in initialize'
/usr/lib/ruby/vendor_ruby/feed2imap/feed2imap.rb:258:in `each'
/usr/lib/ruby/vendor_ruby/feed2imap/feed2imap.rb:258:in `block in initialize'
/usr/lib/ruby/vendor_ruby/feed2imap/feed2imap.rb:223:in `each'
/usr/lib/ruby/vendor_ruby/feed2imap/feed2imap.rb:223:in `initialize'
/usr/bin/feed2imap:48:in `new'
/usr/bin/feed2imap:48:in `<main>'
F, [2016-11-01T23:28:19.114548 #12885] FATAL -- : We can't recover from IMAP errors, so we are exiting.
2016-11-01 / 23:28:19 ♒♒♒  ☹  => 1  
```

It'd be nice to have the example updated with something like:

```
rrs@learner:/usr/share/doc/feed2imap$ cat ~/.feed2imaprc 
include-images: true
default-email: user@feed2imap.invalid
feeds: 
  - name: feed2imap
    url: http://home.gna.org/feed2imap/feed2imap.rss
    target: maildir:///home/rrs/Maildir/RSS
```
