### ISSUE TITLE
Errors when copying to maildir

### ISSUE THREAD

**Issue by firecat53** [feed2imap/feed2imap#2]
Hey,

I don't know if the error I'm getting is because of a newer ruby version or because of something else...

.feed2imaprc:
```
feeds:
- name: Arch Linux Recent news updates
  url: http://www.archlinux.org/feeds/news/
  target: maildir:///home/firecat53/mail/firecat4153/News
- name: Christian Science Monitor | All Stories
  url: http://www.christiansciencemonitor.com/rss/top.rss
  target: maildir:///home/firecat53/mail/firecat4153/News
- name: CNET News.com
  url: http://news.com.com/2547-1_3-0-5.xml
  target: maildir:///home/firecat53/mail/firecat4153/News
- name: cssplay.co.uk
  url: http://www.stunicholls.myby.co.uk/feed.xml
  target: maildir:///home/firecat53/mail/firecat4153/News
- name: Dieter on the web
  url: http://dieter.plaetinck.be/index.rss
  target: maildir:///home/firecat53/mail/firecat4153/News
- name: Doug Hellmann
  url: http://feeds.doughellmann.com/DougHellmann
  target: maildir:///home/firecat53/mail/firecat4153/News
- name: Extremetech
  url: http://rssnewsapps.ziffdavis.com/extreme.xml
  target: maildir:///home/firecat53/mail/firecat4153/News
```
Error message for $ feed2imap -v
```
I, [2012-04-11T10:47:23.939934 #7572]  INFO -- : Feed2Imap V.1.0 started
I, [2012-04-11T10:47:23.940071 #7572]  INFO -- : Reading configuration file ...
I, [2012-04-11T10:47:23.942730 #7572]  INFO -- : Initializing cache ...
I, [2012-04-11T10:47:23.943053 #7572]  INFO -- : Connecting to IMAP accounts ...
I, [2012-04-11T10:47:23.943103 #7572]  INFO -- : Fetching and filtering feeds ...
I, [2012-04-11T10:47:27.479338 #7572]  INFO -- : Parsing and uploading ...
I, [2012-04-11T10:47:27.816450 #7572]  INFO -- : CNET News.com: 10 new items, 0 updated items.
F, [2012-04-11T10:47:27.817189 #7572] FATAL -- : Exception caught while uploading mail to home/firecat53/mail/firecat4153/News: can't convert Fixnum into String
/usr/lib/ruby/1.9.1/feedparser/html2text-parser.rb:20:in `+'
/usr/lib/ruby/1.9.1/feedparser/html2text-parser.rb:20:in `next_img_index'
/usr/lib/ruby/1.9.1/feedparser/html2text-parser.rb:84:in `unknown_starttag'
/usr/lib/ruby/1.9.1/feedparser/sgml-parser.rb:236:in `finish_starttag'
/usr/lib/ruby/1.9.1/feedparser/sgml-parser.rb:208:in `parse_starttag'
/usr/lib/ruby/1.9.1/feedparser/sgml-parser.rb:89:in `goahead'
/usr/lib/ruby/1.9.1/feedparser/sgml-parser.rb:58:in `feed'
/usr/lib/ruby/1.9.1/feedparser/text-output.rb:11:in `html2text'
/usr/lib/ruby/1.9.1/feedparser/text-output.rb:76:in `to_text'
/usr/lib/ruby/1.9.1/feed2imap/itemtomail.rb:83:in `item_to_mail'
/usr/lib/ruby/1.9.1/feed2imap/feed2imap.rb:255:in `block (2 levels) in initialize'
/usr/lib/ruby/1.9.1/feed2imap/feed2imap.rb:253:in `each'
/usr/lib/ruby/1.9.1/feed2imap/feed2imap.rb:253:in `block in initialize'
/usr/lib/ruby/1.9.1/feed2imap/feed2imap.rb:218:in `each'
/usr/lib/ruby/1.9.1/feed2imap/feed2imap.rb:218:in `initialize'
/usr/bin/feed2imap:48:in `new'
/usr/bin/feed2imap:48:in `<main>'
F, [2012-04-11T10:47:27.817276 #7572] FATAL -- : We can't recover from IMAP errors, so we are exiting.
```

Am I writing the maildir:// path correctly, or is something else going on? I'm afraid my ruby knowledge at the moment is zero....

Thanks!
Scott

ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-linux]
